# **********************************
# * In Kubernetes, a ConfigMap is simply an object for storing configuration data. 
# * Other things, like pods, can access the data in a ConfigMap.
# **********************************/

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  release: {{ $relname }}
  {{- end }}