# **********************************
# * In Kubernetes, a ConfigMap is simply an object for storing configuration data. 
# * Other things, like pods, can access the data in a ConfigMap.
# **********************************/

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
{{ include "mychart.app" . | indent 4 }}
data:
  myvalue: "Hello World"
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ include "mychart.app" . | indent 2 }}
